//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cunstudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anh
    {
        public int ID_Anh { get; set; }
        public Nullable<int> ID_Album { get; set; }
        public Nullable<int> ID_Admin { get; set; }
        public Nullable<int> ID_KhachHang { get; set; }
        public Nullable<bool> HienThi { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Album Album { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
