//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cunstudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.Admins = new HashSet<Admin>();
        }
    
        public int ID_HopDong { get; set; }
        public Nullable<int> ID_KhachHang { get; set; }
        public Nullable<int> ID_Admin { get; set; }
        public Nullable<int> ID_Goi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual GoiDichVu GoiDichVu { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
